/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        setAllowInsecureProtocol(true)        
        url = uri("http://caeneus.fritz.box/repository/caeneus-3/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-web:2.5.0")
    api("org.springframework.boot:spring-boot-starter-actuator:2.5.0")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.5.0")
    implementation("ai.centa:weaves0:0.0.1-SNAPSHOT")
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
description = "spring-boot-complete"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
    repositories {
        maven {
	          // releases
            name = "caeneus"
            setAllowInsecureProtocol(true)
	          credentials(PasswordCredentials::class)
            // only if we have a version and it does not end with SNAPSHOT use the releases
            if (hasProperty("version") && 
                    !property("version").toString().endsWith("-SNAPSHOT")) {
                url = uri("http://caeneus.fritz.box:8081/repository/caeneus-1")
       	        mavenContent {
            	      releasesOnly()
                }
            } else {
                url = uri("http://caeneus.fritz.box:8081/repository/caeneus-2")
       	        mavenContent {
            	      snapshotsOnly()
                }
            }
	      }
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
