/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-web:2.5.0")
    api("org.springframework.boot:spring-boot-starter-actuator:2.5.0")
    api("org.springframework.boot:spring-boot-starter-log4j2:2.5.0")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.5.0")
}

group = "ai.centa"
version = "0.0.1-SNAPSHOT"
description = "utilecoj"
java.sourceCompatibility = JavaVersion.VERSION_1_8

if (hasProperty("group")) println(property("group"))

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }

    repositories {
        maven {
	          // releases
            name = "caeneus"
            setAllowInsecureProtocol(true)
	          credentials {
      		      username = "deployer"
      		      password = "FPa5eN^j"
    	      }
            // only if we have a version and it does not end with SNAPSHOT use the releases
            if (hasProperty("version") && 
                !property("version").toString().endsWith("-SNAPSHOT")) {
                url = uri("http://caeneus.fritz.box:8081/repository/caeneus-1")
       	        mavenContent {
            	      releasesOnly()
                }
            } else {
               url = uri("http://caeneus.fritz.box:8081/repository/caeneus-2")
       	       mavenContent {
            	     snapshotsOnly()
               }
            }
	      }
    }

    tasks.withType<JavaCompile>() {
        options.encoding = "UTF-8"
    }

    tasks.withType<Javadoc>() {
        options.encoding = "UTF-8"
    }
}
